---
dev:
  app_function: routines.app
  aws_region: us-east-1
  profile_name: sbox-ab-django
  project_name: routines-api
  runtime: python3.7
  s3_bucket: nlm-sbox-ab-django-app-djangotest-artifacts-us-east-1
  # Defines a prefix added to all tables in the development environment
  environment_variables:
    PYNAMO_PREFIX: routines_dev_
    PYNAMO_REGION: us-east-1
